# ENA tuning for EC2 networking
net.ipv4.neigh.default.delay_first_probe_time=1
net.ipv4.neigh.default.base_reachable_time_ms=5000
net.ipv4.neigh.default.retrans_time_ms=500
net.ipv4.neigh.default.ucast_solicit=0
net.ipv4.tcp_syn_retries=3
