FROM public.ecr.aws/amazonlinux/amazonlinux:2023

ARG BATS_VERSION=v1.14.0

RUN dnf -y install git make rpm-build openssh-clients && \
    git clone --depth 1 --branch "${BATS_VERSION}" \
        https://github.com/bats-core/bats-core.git /tmp/bats && \
    /tmp/bats/install.sh /usr/local && \
    rm -rf /tmp/bats && \
    dnf clean all
