#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the MIT License. See the LICENSE accompanying this file
# for the specific language governing permissions and limitations under
# the License.

if [ "$#" -eq 1 ]; then
  INTERFACE="${1}"
else
  echo "usage: ${0##*/} <device name>"
  exit 1
fi

if [ $UID -ne 0 ]; then
  echo "error: ${0##*/} must be run as root"
  exit 1
fi

. /etc/sysconfig/network-scripts/ec2net-functions

deactivate_primary
unplug_interface
