#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the MIT License. See the LICENSE accompanying this file
# for the specific language governing permissions and limitations under
# the License.

if [ $UID -ne 0 ]; then
  echo "error: ${0##*/} must be run as root"
  exit 1
fi

logger --tag ec2net "[ec2ifscan] Scanning for unconfigured interfaces"
for dev in $(find /sys/class/net/eth*) ; do
  cfg="/etc/sysconfig/network-scripts/ifcfg-${dev##*/}"
  state=$(cat ${dev}/operstate)
  if [ ! -e "${cfg}" ] && [ "${state}" == "down" ] ; then
    logger --tag ec2net "[ec2ifscan] Configuring ${dev##*/}"
    echo 'add' > ${dev}/uevent
  fi
done
