name: shellcheck and unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install bats shellcheck
    - name: Run checks
      run: make check
